import appointPage from '../../support/pageObject/appointPage'
import loginPage from '../../support/pageObject/loginPage'
const userData = require('../../fixtures/3-katalon-demo-cura/loginData.json')
const bookData = require('../../fixtures/3-katalon-demo-cura/appointData.json')

describe('katalon demo cura - make appointment', () => {
  beforeEach(() => {
    cy.visit('')
    cy.get(loginPage.toggleMenu).click()
    cy.get(loginPage.loginLink).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/profile.php#login')
    loginPage.usernameType(userData.loginSuccess.username)
    loginPage.passwordType(userData.loginSuccess.password)
    cy.get(loginPage.loginButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/#appointment')
    cy.verifyVisibilityAndContent(appointPage.title, 'Make Appointment')
    cy.verifyVisibilityAndContent(appointPage.facilityLabel, 'Facility')
    cy.verifyVisibilityAndContent(appointPage.applyLabel, 'Apply for hospital readmission')
    cy.verifyVisibilityAndContent(appointPage.programLabel, 'Healthcare Program')
    cy.verifyVisibilityAndContent(appointPage.dateLabel, 'Visit Date (Required)')
    cy.verifyVisibilityAndContent(appointPage.commentLabel, 'Comment')
  })
  // ------------------------------------------------------------------------
  // positive scenarios
  // selected value; source: https://glebbahmutov.com/cypress-examples/recipes/selected-value.html#option-s-value
  // testing buttons in make appointment page (footer buttons in footer.cy.js)
  it('"make appointment" button clicked', () => {
    cy.verifyVisibilityAndContent(appointPage.makeAppointment, 'Make Appointment')
    cy.get(appointPage.makeAppointment).click()
  })
  it('"cura healthcare" button clicked', () => {
    cy.get(appointPage.toggleMenu).click()
    cy.verifyVisibilityAndContent(appointPage.sidebar, 'CURA Healthcare')
    cy.get(appointPage.sidebar).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('"home" button clicked', () => {
    cy.get(appointPage.toggleMenu).click()
    cy.verifyVisibilityAndContent(appointPage.homeLink, 'Home')
    cy.get(appointPage.homeLink).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('"history" button clicked', () => {
    cy.get(appointPage.toggleMenu).click()
    cy.verifyVisibilityAndContent(appointPage.historyLink, 'History')
    cy.get(appointPage.historyLink).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/history.php#history')
  })
  it('"profile" button clicked', () => {
    cy.get(appointPage.toggleMenu).click()
    cy.verifyVisibilityAndContent(appointPage.profileLink, 'Profile')
    cy.get(appointPage.profileLink).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/profile.php#profile')
  })
  it('success - all valid entries (hongkong facility, medicaid program)', () => {
    cy.get('select')
      .select('Hongkong CURA Healthcare Center')
      .invoke('val')
      .then((value) => {
        expect(value).to.equal('Hongkong CURA Healthcare Center')
      })
    cy.get(appointPage.applyField).click()
    cy.get(appointPage.radioButton2).check()
    cy.get(appointPage.radioButton2).should('be.checked')
    cy.get(appointPage.radioButton2).should('have.value', 'Medicaid')
    cy.get(appointPage.calendarIcon).click()
    cy.get(appointPage.dateNumber).click()
    cy.get(appointPage.commentField).click({ force: true })
    cy.get(appointPage.commentField).type(bookData.comment)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', 'Hongkong CURA Healthcare Center')
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'Yes')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', 'Medicaid')
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.commentSummary).should('contain.text', bookData.comment)
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, tokyo facility (default program)', () => {
    cy.get('select')
      .select(bookData.defaultFacility)
      .invoke('val')
      .then((value) => {
        expect(value).to.equal(bookData.defaultFacility)
      })
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, hongkong facility (default program)', () => {
    cy.get('select')
      .select('Hongkong CURA Healthcare Center')
      .invoke('val')
      .then((value) => {
        expect(value).to.equal('Hongkong CURA Healthcare Center')
      })
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', 'Hongkong CURA Healthcare Center')
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, seoul facility (default program)', () => {
    cy.get('select')
      .select('Seoul CURA Healthcare Center')
      .invoke('val')
      .then((value) => {
        expect(value).to.equal('Seoul CURA Healthcare Center')
      })
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', 'Seoul CURA Healthcare Center')
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date (default facility & program)', () => {
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, apply clicked (default facility & program)', () => {
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    cy.get(appointPage.applyField).click()
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'Yes')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, medicaid clicked (default facility)', () => {
    cy.get(appointPage.radioButton2).click()
    cy.get(appointPage.radioButton2).should('be.checked')
    cy.get(appointPage.radioButton2).should('have.value', 'Medicaid')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', 'Medicaid')
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  it('success - empty comment, valid date, none clicked (default facility)', () => {
    cy.get(appointPage.radioButton3).click()
    cy.get(appointPage.radioButton3).should('be.checked')
    cy.get(appointPage.radioButton3).should('have.value', 'None')
    appointPage.dateType(bookData.date)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', 'None')
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.date)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
  // ------------------------------------------------------------------------
  // negative scenarios
  // html5 form validation:
  // source: https://stackoverflow.com/questions/71239608/cypress-testing-that-a-browser-specific-alert-exists-when-submitting-invalid-i
  //         https://glebbahmutov.com/blog/form-validation-in-cypress/
  it('failed - empty date & comment (default facility & program)', () => {
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    cy.get(appointPage.bookButton).click()
    cy.get('input:invalid').then(($input) => {
      expect($input[0].validationMessage).to.eq('Please fill out this field.')
    })
  })
  it('failed - empty date (default facility & program)', () => {
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.commentType(bookData.comment)
    cy.get(appointPage.bookButton).click()
    cy.get('input:invalid').then(($input) => {
      expect($input[0].validationMessage).to.eq('Please fill out this field.')
    })
  })
  it('success - invalid date, empty comment (default facility & program)', () => {
    cy.get(appointPage.radioButton1).should('be.checked')
    cy.get(appointPage.radioButton1).should('have.value', 'Medicare')
    appointPage.dateType(bookData.invalidDate)
    cy.get(appointPage.bookButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/appointment.php#summary')
    cy.verifyVisibilityAndContent(appointPage.confirmTitle, 'Appointment Confirmation')
    cy.verifyVisibilityAndContent(appointPage.confirmSubtitle, 'Please be informed that your appointment has been booked as following:')
    cy.verifyVisibilityAndContent(appointPage.facilityLabelSummary, 'Facility')
    cy.get(appointPage.facilitySummary).should('contain.text', bookData.defaultFacility)
    cy.verifyVisibilityAndContent(appointPage.applyLabelSummary, 'Apply for hospital readmission')
    cy.get(appointPage.applySummary).should('contain.text', 'No')
    cy.verifyVisibilityAndContent(appointPage.programLabelSummary, 'Healthcare Program')
    cy.get(appointPage.programSummary).should('contain.text', bookData.defaultProgram)
    cy.verifyVisibilityAndContent(appointPage.dateLabelSummary, 'Visit Date')
    cy.get(appointPage.dateSummary).should('contain.text', bookData.invalidDate)
    cy.verifyVisibilityAndContent(appointPage.commentLabelSummary, 'Comment')
    cy.get(appointPage.homepageButton).click()
    cy.url().should('eq', Cypress.config().baseUrl + '/')
  })
})