name: Katalon Demo Cura Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run katalon demo cura tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/3-katalon-demo-cura/*.cy.js